# Generated by Django 4.2.25 on 2025-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yandex_market_link',
            field=models.URLField(blank=True, null=True, verbose_name='Yandex Market havola'),
        ),
    ]
