# Generated by Django 4.2.25 on 2025-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_yandex_market_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='Chegirma foizi (0-100)'),
        ),
    ]
