# Generated by Django 4.2.25 on 2025-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi")),
            ],
            options={
                'verbose_name': 'Murojat',
                'verbose_name_plural': 'Murojatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
